name: Build & Publish Reviews

on:
  push:
    branches: [ reviews_branch ]
    paths:
      - 'reviews/*.md'
      - 'scripts/build-reviews.js'
      - 'scripts/validate-reviews.js'
      - '.github/workflows/update-reviews.yml'

permissions:
  contents: write # For git push
  pages: write # For GitHub Pages deploy
  id-token: write

jobs:
  process_reviews:
    runs-on: ubuntu-latest
    outputs:
      reviews_changed: ${{ steps.build.outputs.changed }}
      
    steps:
      - name: Checkout reviews branch
        uses: actions/checkout@v4
        with:
          ref: reviews_branch
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Validate reviews format
        run: npm run validate

      - name: Build reviews JSON
        id: build
        run: |
          echo "Building reviews.json..."
          npm run build
            
          # Check if reviews.json changed
          if git diff --quiet public/reviews.json 2>/dev/null; then
            echo "No changes in reviews.json"
            echo "changed=false" >> $GITHUB_OUTPUT
            else
            echo "Reviews.json updated"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 📋 Generate build summary
        if: steps.build.outputs.changed == 'true'
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- Reviews processados: $(jq length public/reviews.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Tamanho do arquivo: $(du -h public/reviews.json | cut -f1)" >> $GITHUB_STEP_SUMMARY

      - name: Merge into master
        if: steps.build.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
            
          # Checkout master and merge
          git checkout master
          git merge --no-ff reviews_branch -m "🚀 chore: update reviews.json
            
          - Reviews processados: $(jq length public/reviews.json)
          - Build timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
            
          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            
          git push origin master

  deploy_pages:
    needs: process_reviews
    if: needs.process_reviews.outputs.reviews_changed == 'true'
    runs-on: ubuntu-latest
    
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify_completion:
    needs: [process_reviews, deploy_pages]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Report status
        run: |
          if [ "${{ needs.process_reviews.result }}" = "success" ] && [ "${{ needs.deploy_pages.result }}" = "success" ]; then
            echo "Reviews processados e publicados com sucesso!"
            echo "Site atualizado: ${{ needs.deploy_pages.outputs.page_url || 'https://hiperim.github.io/SeuCanto/' }}"
          elif [ "${{ needs.process_reviews.outputs.reviews_changed }}" = "false" ]; then
            echo "Nenhuma mudança detectada nos reviews"
          else
            echo "Falha no processamento ou deploy dos reviews"
            echo "Verifique os logs para mais detalhes"
          fi
